# Workflow: Deploy static HTML from 'Sites' branch to GitHub Pages
name: Deploy static HTML to GitHub Pages

on:
  push:
    branches: ["Sites"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .nojekyll to disable Jekyll
        run: echo "" > .nojekyll

      - name: Debug – list files to upload
        run: ls -la

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload HTML as GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Ensure index.html is at root

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
